version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    build: nginx/
    restart: on-failure
    links:
      - server_1
      - server_2
    depends_on:
      - server_1
      - server_2

  consumer:
    restart: on-failure
    image: link_consumer
    build:
      context: .
      dockerfile: ./Jobs.LinkConsumer/Dockerfile
    links:
      - db
      - rabbitmq
    depends_on:
      - rabbitmq

  server_1:
    restart: on-failure
    image: docker_test_backend
    build:
      context: .
      dockerfile: ./DockerTest.Web/Dockerfile
    links:
      - db
      - rabbitmq
    volumes:
      - ./files/:/app/wwwroot/files/
    ports:
      - 80
    depends_on:
      - rabbitmq

  server_2:
    restart: on-failure
    image: docker_test_backend
    build:
      context: .
      dockerfile: ./DockerTest.Web/Dockerfile
    links:
      - db
      - rabbitmq
    volumes:
      - ./files/:/app/wwwroot/files/
    ports:
      - 80
    depends_on:
      - rabbitmq

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dockerTestDB
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/pg/:/var/lib/postgresql/data/
    ports:
      - 127.0.0.1:5432:5432

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "hackerdmitry"
      RABBITMQ_DEFAULT_PASS: "e2b72411-ebb9-40ab-8add-40f6fab4fce5"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 10s
      retries: 6

  redis:
    image: redis
    ports:
    - 127.0.0.1:6379:6379
#    environment:
#      REDIS_PASSWORD: "50515410-a1f7-41ee-b657-13082cd706f7"